# Generated by Django 2.0.3 on 2018-06-28 08:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_img', models.URLField()),
                ('title', models.CharField(max_length=254)),
                ('author', models.CharField(max_length=254)),
                ('publishing_year', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[1-2]\\d{3,3}$', 'Not a valid year')])),
                ('language', models.CharField(choices=[('it', 'Italiano'), ('en', 'Inglese'), ('de', 'Tedesco'), ('es', 'Spagnolo')], max_length=10)),
                ('isbn', models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=10)])),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user_is_using_the_copy', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_destination', models.CharField(choices=[('to_consult', 'Consultazione in sede'), ('to_rent', 'Destinato al prestito')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted_on', models.DateField()),
                ('started_on', models.DateField(null=True)),
                ('finished_on', models.DateField(null=True)),
                ('renewed_on', models.DateField(null=True)),
                ('ready_for_withdraw', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QueueOfRentReservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=254)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudyHallSeat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='StudyHallSeatReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_user_inside_study_hall', models.BooleanField(default=False)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_services.StudyHallSeat')),
            ],
        ),
    ]
