# Generated by Django 2.0.3 on 2018-06-28 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studyhallseatreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queueofrentreservations',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_services.Book'),
        ),
        migrations.AddField(
            model_name='queueofrentreservations',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='book_copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_services.Copy'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='copy',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_services.Book'),
        ),
        migrations.AddField(
            model_name='copy',
            name='on_shelf',
            field=models.ForeignKey(on_delete=models.SET(None), to='library_services.Shelf'),
        ),
        migrations.AddField(
            model_name='consultationreservation',
            name='copy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_services.Copy'),
        ),
        migrations.AddField(
            model_name='consultationreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='studyhallseatreservation',
            unique_together={('seat', 'date', 'user')},
        ),
    ]
